name: WebDriverIO Tests

on:
  push:
        branches:
          - main

jobs:
  webdriverio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Add NodeSource repository
        run: |
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x focal main" | sudo tee /etc/apt/sources.list.d/nodesource.list
          echo "deb-src [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_14.x focal main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
          sudo apt-get update
          sudo apt-get install -y nodejs

      - name: Install dependencies with --unsafe-perm and wdio-chromedriver-service
        run: |
          npm install --unsafe-perm --force
          npm install wdio-chromedriver-service --save-dev

      - name: Set TZ environment variable
        run: |
          export TZ='Pacific/Auckland'

      - name: Create folders for Selenium Grid
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p ./reports/json/tmp
          mkdir -p ./reports/junit

      - name: Run WebDriverIO tests in Selenium Grid
        run: |
          npx wdio wdio.conf.js --cucumberOpts.tagExpression="@smoketest" --headless --log=ERROR --maxInstances=20
        continue-on-error: true

      - name: Compress HTML Artifacts
        run: |
          zip -r "./DiamondereTestReport.zip" ./reports/html
        working-directory: ${{ github.workspace }}

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: "./DiamondereTestReport.zip"

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3.7.1
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: qa@litefury.com
          password: wpra uabk nhiz cmtq
          subject: "Diamondere Automation Report"
          to: ashok@litefury.com, pradeep.ac@litefury.com, resshmaa@litefury.com, rajeev@diamondere.com
          from: Test Suite
          attachments: "./DiamondereTestReport.zip"

      - name: Notify Google Space
        run: |
          ARTIFACT_URL="https://github.com/QualAssured/Diamondere/actions/runs/${{ github.run_id }}"
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "Diamondere UI Automation pipeline has run, To View the results select below link and download Artifact: [Artifact Link]('"$ARTIFACT_URL"')" 
          }' "https://chat.googleapis.com/v1/spaces/AAAA0YcuuUU/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=QgXMWEKoe8v-PLIVw3ONIyttpuKIvqA-8gmK6g_u79g"
